"""
DataPulse - ML Feature Engineering

Purpose
-------
Build reusable, analysis-ready machine-learning features from the
validated e-commerce dataset.

This module sits between:
    Analytics -> Feature Engineering -> ML Models

Supported ML workflows
-----------------------
1. Customer churn prediction
2. Customer segmentation
3. Sales forecasting
4. Sales anomaly detection

Important
---------
- Does NOT perform EDA.
- Does NOT modify the original dataframe.
- Uses the schema mapping generated by schema_mapper.py.
- Handles missing optional fields gracefully.
- Produces stable feature tables for downstream ML modules.

Stable interface
----------------
build_ml_features(df, mapping) -> dict
"""

from __future__ import annotations

from typing import Any, Dict, Optional

import numpy as np
import pandas as pd


# ---------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------

CUSTOMER_FIELDS = [
    "customer_id",
    "customer_name",
]

PRODUCT_FIELDS = [
    "product_id",
    "product_name",
    "category",
    "subcategory",
    "brand",
]

SELLER_FIELDS = [
    "seller_id",
    "seller_name",
]

GEOGRAPHIC_FIELDS = [
    "region",
    "market",
]

FINANCIAL_FIELDS = [
    "sales_amount",
    "quantity",
    "unit_price",
    "cost",
    "profit",
]

DATE_FIELDS = [
    "order_date",
]

OPTIONAL_FIELDS = (
    CUSTOMER_FIELDS
    + PRODUCT_FIELDS
    + SELLER_FIELDS
    + GEOGRAPHIC_FIELDS
    + FINANCIAL_FIELDS
    + DATE_FIELDS
    + [
        "order_id",
        "order_status",
        "discount",
        "campaign_id",
        "channel",
        "payment_method",
        "device_type",
    ]
)


# ---------------------------------------------------------------------
# Generic helpers
# ---------------------------------------------------------------------

def _get_source_column(
    mapping: Dict[str, Any],
    canonical_field: str,
) -> Optional[str]:
    """
    Return the original dataframe column mapped to a canonical field.
    """

    if not mapping:
        return None

    mappings = mapping.get(
        "mappings",
        {},
    )

    value = mappings.get(
        canonical_field
    )

    if isinstance(value, dict):
        return (
            value.get("source_column")
            or value.get("column")
        )

    if isinstance(value, str):
        return value

    return None


def _safe_numeric(
    series: pd.Series,
) -> pd.Series:
    return pd.to_numeric(
        series,
        errors="coerce",
    )


def _safe_text(
    series: pd.Series,
    default: str = "Unknown",
) -> pd.Series:
    result = (
        series.astype("string")
        .str.strip()
    )

    result = result.replace(
        {
            "": pd.NA,
            "nan": pd.NA,
            "None": pd.NA,
            "null": pd.NA,
        }
    )

    return result.fillna(default)


def _safe_divide(
    numerator: pd.Series,
    denominator: pd.Series,
) -> pd.Series:
    numerator = pd.to_numeric(
        numerator,
        errors="coerce",
    ).fillna(0)

    denominator = pd.to_numeric(
        denominator,
        errors="coerce",
    )

    return (
        numerator
        .div(
            denominator.replace(
                0,
                np.nan,
            )
        )
        .replace(
            [np.inf, -np.inf],
            np.nan,
        )
        .fillna(0)
    )


def _empty_dataframe(
    columns: list[str],
) -> pd.DataFrame:
    return pd.DataFrame(
        columns=columns
    )


# ---------------------------------------------------------------------
# Standardized dataframe
# ---------------------------------------------------------------------

def _prepare_dataframe(
    df: pd.DataFrame,
    mapping: Dict[str, Any],
) -> pd.DataFrame:
    """
    Build a standardized internal dataframe using canonical names.
    """

    working = pd.DataFrame(
        index=df.index
    )

    for field in OPTIONAL_FIELDS:

        source_column = _get_source_column(
            mapping,
            field,
        )

        if (
            source_column
            and source_column in df.columns
        ):
            working[field] = df[
                source_column
            ]

    # Numeric fields
    for field in FINANCIAL_FIELDS:
        if field in working.columns:
            working[field] = _safe_numeric(
                working[field]
            )

    # Text fields
    text_fields = (
        CUSTOMER_FIELDS
        + PRODUCT_FIELDS
        + SELLER_FIELDS
        + GEOGRAPHIC_FIELDS
        + [
            "order_id",
            "order_status",
            "campaign_id",
            "channel",
            "payment_method",
            "device_type",
        ]
    )

    for field in text_fields:
        if field in working.columns:
            working[field] = _safe_text(
                working[field]
            )

    # Dates
    for field in DATE_FIELDS:
        if field in working.columns:
            working[field] = pd.to_datetime(
                working[field],
                errors="coerce",
            )

    return working


# ---------------------------------------------------------------------
# Financial feature preparation
# ---------------------------------------------------------------------

def _prepare_financial_features(
    working: pd.DataFrame,
) -> pd.DataFrame:
    """
    Add derived financial features.
    """

    result = working.copy()

    if (
        "profit" not in result.columns
        and "sales_amount" in result.columns
        and "cost" in result.columns
    ):
        result["profit"] = (
            result["sales_amount"]
            - result["cost"]
        )

    if (
        "unit_price" not in result.columns
        and "sales_amount" in result.columns
        and "quantity" in result.columns
    ):
        result["unit_price"] = _safe_divide(
            result["sales_amount"],
            result["quantity"],
        )

    if (
        "profit" in result.columns
        and "sales_amount" in result.columns
    ):
        result["profit_margin"] = _safe_divide(
            result["profit"] * 100,
            result["sales_amount"],
        )
    else:
        result["profit_margin"] = 0.0

    if (
        "discount" in result.columns
    ):
        discount = result["discount"]

        valid = discount.dropna()

        if (
            not valid.empty
            and valid.abs().quantile(
                0.95
            ) <= 1
        ):
            discount = discount * 100

        result["discount_pct"] = (
            discount
            .clip(lower=0)
            .fillna(0)
        )

    else:
        result["discount_pct"] = 0.0

    return result


# ---------------------------------------------------------------------
# Date features
# ---------------------------------------------------------------------

def _build_date_features(
    working: pd.DataFrame,
) -> pd.DataFrame:
    """
    Build calendar features useful for forecasting and anomaly
    detection.
    """

    result = working.copy()

    if "order_date" not in result.columns:
        return result

    date = result["order_date"]

    result["order_year"] = date.dt.year
    result["order_month"] = date.dt.month
    result["order_quarter"] = date.dt.quarter
    result["order_week"] = date.dt.isocalendar().week.astype(
        "Int64"
    )
    result["order_day"] = date.dt.day
    result["order_day_of_week"] = (
        date.dt.dayofweek
    )
    result["order_day_name"] = (
        date.dt.day_name()
    )
    result["order_weekend"] = (
        date.dt.dayofweek >= 5
    ).astype(int)

    result["year_month"] = (
        date.dt.to_period("M")
        .astype("string")
    )

    result["year_week"] = (
        date.dt.to_period("W")
        .astype("string")
    )

    return result


# ---------------------------------------------------------------------
# Customer-level features
# ---------------------------------------------------------------------

def _build_customer_features(
    working: pd.DataFrame,
) -> pd.DataFrame:
    """
    Build customer-level features.

    These features are designed to support:
    - churn
    - segmentation
    - customer value analysis
    """

    required = {
        "customer_id",
        "order_date",
    }

    if not required.issubset(
        working.columns
    ):
        return _empty_dataframe(
            [
                "customer_id",
                "revenue",
                "orders",
                "quantity",
                "profit",
                "average_order_value",
                "recency_days",
                "lifetime_days",
                "purchase_frequency",
                "avg_days_between_orders",
                "profit_margin",
                "discount_rate",
            ]
        )

    data = working.dropna(
        subset=[
            "customer_id",
            "order_date",
        ]
    ).copy()

    if data.empty:
        return _empty_dataframe(
            [
                "customer_id",
                "revenue",
                "orders",
                "quantity",
                "profit",
                "average_order_value",
                "recency_days",
                "lifetime_days",
                "purchase_frequency",
                "avg_days_between_orders",
                "profit_margin",
                "discount_rate",
            ]
        )

    reference_date = (
        data["order_date"]
        .max()
        + pd.Timedelta(days=1)
    )

    aggregations = {
        "revenue": (
            "sales_amount",
            "sum",
        ),
        "orders": (
            "order_id",
            "nunique",
        )
        if "order_id" in data.columns
        else (
            "sales_amount",
            "size",
        ),
        "quantity": (
            "quantity",
            "sum",
        )
        if "quantity" in data.columns
        else (
            "sales_amount",
            "size",
        ),
        "profit": (
            "profit",
            "sum",
        )
        if "profit" in data.columns
        else (
            "sales_amount",
            lambda x: 0.0,
        ),
        "first_purchase": (
            "order_date",
            "min",
        ),
        "last_purchase": (
            "order_date",
            "max",
        ),
        "average_discount_pct": (
            "discount_pct",
            "mean",
        ),
    }

    customer = (
        data.groupby(
            "customer_id",
            dropna=False,
        )
        .agg(**aggregations)
        .reset_index()
    )

    customer["average_order_value"] = (
        _safe_divide(
            customer["revenue"],
            customer["orders"],
        )
    )

    customer["recency_days"] = (
        reference_date
        - customer["last_purchase"]
    ).dt.days

    customer["lifetime_days"] = (
        customer["last_purchase"]
        - customer["first_purchase"]
    ).dt.days

    customer["lifetime_days"] = (
        customer["lifetime_days"]
        .clip(lower=0)
    )

    customer["purchase_frequency"] = (
        _safe_divide(
            customer["orders"],
            customer["lifetime_days"]
            + 1,
        )
    )

    # Calculate average gap between purchases.
    gap_values = []

    for customer_id, group in data.groupby(
        "customer_id"
    ):
        dates = (
            group["order_date"]
            .dropna()
            .sort_values()
            .drop_duplicates()
        )

        if len(dates) <= 1:
            gap = 0.0
        else:
            gap = float(
                dates.diff()
                .dt.days
                .dropna()
                .mean()
            )

        gap_values.append(
            {
                "customer_id": customer_id,
                "avg_days_between_orders": gap,
            }
        )

    gap_df = pd.DataFrame(
        gap_values
    )

    if not gap_df.empty:
        customer = customer.merge(
            gap_df,
            on="customer_id",
            how="left",
        )
    else:
        customer[
            "avg_days_between_orders"
        ] = 0.0

    customer["profit_margin"] = (
        _safe_divide(
            customer["profit"] * 100,
            customer["revenue"],
        )
    )

    customer["discount_rate"] = (
        customer["average_discount_pct"]
        .fillna(0)
    )

    # Repeat-customer flag
    customer["is_repeat_customer"] = (
        customer["orders"] >= 2
    ).astype(int)

    # RFM-style scoring
    customer["recency_score"] = (
        pd.qcut(
            customer["recency_days"]
            .rank(
                method="first"
            ),
            5,
            labels=False,
            duplicates="drop",
        )
    )

    # Reverse recency score so lower recency = better.
    if customer["recency_score"].notna().any():
        customer["recency_score"] = (
            customer["recency_score"]
            .max()
            - customer["recency_score"]
            + 1
        )

    customer["frequency_score"] = (
        pd.qcut(
            customer["orders"]
            .rank(
                method="first"
            ),
            5,
            labels=False,
            duplicates="drop",
        )
        + 1
    )

    customer["monetary_score"] = (
        pd.qcut(
            customer["revenue"]
            .rank(
                method="first"
            ),
            5,
            labels=False,
            duplicates="drop",
        )
        + 1
    )

    customer[
        "recency_score"
    ] = pd.to_numeric(
        customer["recency_score"],
        errors="coerce",
    ).fillna(1)

    customer[
        "frequency_score"
    ] = pd.to_numeric(
        customer["frequency_score"],
        errors="coerce",
    ).fillna(1)

    customer[
        "monetary_score"
    ] = pd.to_numeric(
        customer["monetary_score"],
        errors="coerce",
    ).fillna(1)

    customer["rfm_score"] = (
        customer["recency_score"]
        + customer["frequency_score"]
        + customer["monetary_score"]
    )

    customer["ltv_proxy"] = (
        customer["average_order_value"]
        * customer["purchase_frequency"]
        * 365
    )

    customer["annualized_revenue_proxy"] = (
        customer["revenue"]
        / (
            customer["lifetime_days"]
            .clip(lower=1)
            / 365
        )
    )

    return customer.sort_values(
        "revenue",
        ascending=False,
    ).reset_index(
        drop=True
    )


# ---------------------------------------------------------------------
# Product-level features
# ---------------------------------------------------------------------

def _build_product_features(
    working: pd.DataFrame,
) -> pd.DataFrame:
    """Build product-level ML features."""

    product_field = None

    if "product_id" in working.columns:
        product_field = "product_id"

    elif "product_name" in working.columns:
        product_field = "product_name"

    if product_field is None:
        return _empty_dataframe(
            [
                "product",
                "revenue",
                "quantity",
                "orders",
                "profit",
                "average_unit_price",
                "average_discount_pct",
                "profit_margin",
            ]
        )

    result = (
        working.groupby(
            product_field,
            dropna=False,
        )
        .agg(
            revenue=(
                "sales_amount",
                "sum",
            ),
            quantity=(
                "quantity",
                "sum",
            )
            if "quantity" in working.columns
            else (
                "sales_amount",
                "size",
            ),
            orders=(
                "order_id",
                "nunique",
            )
            if "order_id" in working.columns
            else (
                "sales_amount",
                "size",
            ),
            profit=(
                "profit",
                "sum",
            )
            if "profit" in working.columns
            else (
                "sales_amount",
                lambda x: 0.0,
            ),
            average_unit_price=(
                "unit_price",
                "mean",
            )
            if "unit_price" in working.columns
            else (
                "sales_amount",
                "mean",
            ),
            average_discount_pct=(
                "discount_pct",
                "mean",
            ),
        )
        .reset_index()
        .rename(
            columns={
                product_field: "product"
            }
        )
    )

    result["profit_margin"] = (
        _safe_divide(
            result["profit"] * 100,
            result["revenue"],
        )
    )

    return result.sort_values(
        "revenue",
        ascending=False,
    ).reset_index(
        drop=True
    )


# ---------------------------------------------------------------------
# Sales time-series features
# ---------------------------------------------------------------------

def _build_sales_time_series(
    working: pd.DataFrame,
) -> pd.DataFrame:
    """
    Build monthly sales time series.

    Includes lag and rolling features required by forecasting and
    anomaly detection.
    """

    required = {
        "order_date",
        "sales_amount",
    }

    if not required.issubset(
        working.columns
    ):
        return _empty_dataframe(
            [
                "period",
                "revenue",
                "orders",
                "quantity",
                "profit",
            ]
        )

    data = working.dropna(
        subset=[
            "order_date"
        ]
    ).copy()

    if data.empty:
        return _empty_dataframe(
            [
                "period",
                "revenue",
                "orders",
                "quantity",
                "profit",
            ]
        )

    data["period"] = (
        data["order_date"]
        .dt.to_period("M")
        .dt.to_timestamp()
    )

    result = (
        data.groupby(
            "period"
        )
        .agg(
            revenue=(
                "sales_amount",
                "sum",
            ),
            orders=(
                "order_id",
                "nunique",
            )
            if "order_id" in data.columns
            else (
                "sales_amount",
                "size",
            ),
            quantity=(
                "quantity",
                "sum",
            )
            if "quantity" in data.columns
            else (
                "sales_amount",
                "size",
            ),
            profit=(
                "profit",
                "sum",
            )
            if "profit" in data.columns
            else (
                "sales_amount",
                lambda x: 0.0,
            ),
        )
        .reset_index()
        .sort_values(
            "period"
        )
        .reset_index(
            drop=True
        )
    )

    # Growth
    result["revenue_change"] = (
        result["revenue"].diff()
    )

    result["revenue_growth_pct"] = (
        result["revenue"]
        .pct_change()
        .replace(
            [np.inf, -np.inf],
            np.nan,
        )
        * 100
    )

    # Lags
    result["revenue_lag_1"] = (
        result["revenue"].shift(1)
    )

    result["revenue_lag_2"] = (
        result["revenue"].shift(2)
    )

    result["revenue_lag_3"] = (
        result["revenue"].shift(3)
    )

    # Rolling averages
    result["revenue_rolling_3"] = (
        result["revenue"]
        .rolling(
            window=3,
            min_periods=1,
        )
        .mean()
    )

    result["revenue_rolling_6"] = (
        result["revenue"]
        .rolling(
            window=6,
            min_periods=1,
        )
        .mean()
    )

    # Rolling volatility
    result["revenue_rolling_std_3"] = (
        result["revenue"]
        .rolling(
            window=3,
            min_periods=2,
        )
        .std()
        .fillna(0)
    )

    # Time index
    result["time_index"] = np.arange(
        len(result)
    )

    result["month_number"] = (
        result["period"].dt.month
    )

    result["quarter"] = (
        result["period"].dt.quarter
    )

    return result


# ---------------------------------------------------------------------
# Transaction-level anomaly features
# ---------------------------------------------------------------------

def _build_anomaly_features(
    working: pd.DataFrame,
) -> pd.DataFrame:
    """
    Build transaction-level anomaly features.

    These features can be consumed by Isolation Forest or other
    anomaly detection models.
    """

    if "sales_amount" not in working.columns:
        return _empty_dataframe(
            [
                "sales_amount",
                "quantity",
                "unit_price",
                "profit",
                "discount_pct",
            ]
        )

    data = working.copy()

    features = pd.DataFrame(
        index=data.index
    )

    features["sales_amount"] = (
        data["sales_amount"]
        .fillna(
            data["sales_amount"].median()
        )
    )

    if "quantity" in data.columns:
        features["quantity"] = (
            data["quantity"]
            .fillna(
                data["quantity"].median()
            )
        )
    else:
        features["quantity"] = 0.0

    if "unit_price" in data.columns:
        features["unit_price"] = (
            data["unit_price"]
            .fillna(
                data["unit_price"].median()
            )
        )
    else:
        features["unit_price"] = (
            _safe_divide(
                features["sales_amount"],
                features["quantity"],
            )
        )

    if "profit" in data.columns:
        features["profit"] = (
            data["profit"]
            .fillna(0)
        )
    else:
        features["profit"] = 0.0

    if "discount_pct" in data.columns:
        features["discount_pct"] = (
            data["discount_pct"]
            .fillna(0)
        )
    else:
        features["discount_pct"] = 0.0

    if "order_date" in data.columns:
        features["day_of_week"] = (
            data["order_date"]
            .dt.dayofweek
            .fillna(0)
        )

        features["month"] = (
            data["order_date"]
            .dt.month
            .fillna(0)
        )
    else:
        features["day_of_week"] = 0
        features["month"] = 0

    # Log transformation helps models handle highly skewed sales.
    features["log_sales_amount"] = np.log1p(
        features["sales_amount"].clip(
            lower=0
        )
    )

    features["log_quantity"] = np.log1p(
        features["quantity"].clip(
            lower=0
        )
    )

    # Margin
    features["profit_margin"] = (
        _safe_divide(
            features["profit"] * 100,
            features["sales_amount"],
        )
    )

    return features.reset_index(
        drop=True
    )


# ---------------------------------------------------------------------
# Feature metadata
# ---------------------------------------------------------------------

def _build_feature_metadata(
    customer_features: pd.DataFrame,
    product_features: pd.DataFrame,
    sales_time_series: pd.DataFrame,
    anomaly_features: pd.DataFrame,
) -> Dict[str, Any]:
    """Describe generated ML feature sets."""

    return {
        "customer_features": {
            "available": not customer_features.empty,
            "rows": int(
                len(customer_features)
            ),
            "features": list(
                customer_features.columns
            ),
        },
        "product_features": {
            "available": not product_features.empty,
            "rows": int(
                len(product_features)
            ),
            "features": list(
                product_features.columns
            ),
        },
        "sales_time_series": {
            "available": not sales_time_series.empty,
            "rows": int(
                len(sales_time_series)
            ),
            "features": list(
                sales_time_series.columns
            ),
        },
        "anomaly_features": {
            "available": not anomaly_features.empty,
            "rows": int(
                len(anomaly_features)
            ),
            "features": list(
                anomaly_features.columns
            ),
        },
    }


# ---------------------------------------------------------------------
# Capability detection
# ---------------------------------------------------------------------

def _build_capabilities(
    working: pd.DataFrame,
    customer_features: pd.DataFrame,
    product_features: pd.DataFrame,
    sales_time_series: pd.DataFrame,
    anomaly_features: pd.DataFrame,
) -> Dict[str, bool]:
    """Determine which ML pipelines have usable feature sets."""

    return {
        "churn_features": (
            not customer_features.empty
            and "customer_id"
            in customer_features.columns
            and "recency_days"
            in customer_features.columns
        ),
        "segmentation_features": (
            not customer_features.empty
            and "customer_id"
            in customer_features.columns
            and len(customer_features) >= 3
        ),
        "forecasting_features": (
            not sales_time_series.empty
            and len(sales_time_series) >= 3
        ),
        "anomaly_features": (
            not anomaly_features.empty
            and len(anomaly_features) >= 5
        ),
        "product_features": (
            not product_features.empty
        ),
    }


# ---------------------------------------------------------------------
# Main public function
# ---------------------------------------------------------------------

def build_ml_features(
    df: pd.DataFrame,
    mapping: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Build all reusable ML feature sets.

    Returns
    -------
    dict
        Stable feature-engineering contract:

        {
            "available": bool,
            "customer_features": DataFrame,
            "product_features": DataFrame,
            "sales_time_series": DataFrame,
            "anomaly_features": DataFrame,
            "metadata": dict,
            "capabilities": dict,
            "warnings": list,
        }
    """

    if (
        df is None
        or not isinstance(df, pd.DataFrame)
        or df.empty
    ):
        return {
            "available": False,
            "customer_features": pd.DataFrame(),
            "product_features": pd.DataFrame(),
            "sales_time_series": pd.DataFrame(),
            "anomaly_features": pd.DataFrame(),
            "metadata": {},
            "capabilities": {},
            "warnings": [
                "A non-empty pandas DataFrame is required."
            ],
        }

    # Standardize according to schema mapping.
    working = _prepare_dataframe(
        df,
        mapping,
    )

    # Derived financial features.
    working = _prepare_financial_features(
        working
    )

    # Calendar features.
    working = _build_date_features(
        working
    )

    # Customer ML features.
    customer_features = (
        _build_customer_features(
            working
        )
    )

    # Product features.
    product_features = (
        _build_product_features(
            working
        )
    )

    # Forecasting time series.
    sales_time_series = (
        _build_sales_time_series(
            working
        )
    )

    # Transaction anomaly features.
    anomaly_features = (
        _build_anomaly_features(
            working
        )
    )

    capabilities = _build_capabilities(
        working,
        customer_features,
        product_features,
        sales_time_series,
        anomaly_features,
    )

    metadata = _build_feature_metadata(
        customer_features,
        product_features,
        sales_time_series,
        anomaly_features,
    )

    warnings = []

    if not capabilities["churn_features"]:
        warnings.append(
            "Customer churn features are unavailable or insufficient."
        )

    if not capabilities["segmentation_features"]:
        warnings.append(
            "Customer segmentation features are unavailable "
            "or fewer than 3 customers are available."
        )

    if not capabilities["forecasting_features"]:
        warnings.append(
            "Sales forecasting requires at least 3 monthly periods."
        )

    if not capabilities["anomaly_features"]:
        warnings.append(
            "Anomaly detection requires at least 5 usable records."
        )

    return {
        "available": True,
        "customer_features": customer_features,
        "product_features": product_features,
        "sales_time_series": sales_time_series,
        "anomaly_features": anomaly_features,
        "metadata": metadata,
        "capabilities": capabilities,
        "warnings": warnings,
    }


# ---------------------------------------------------------------------
# Convenience helpers
# ---------------------------------------------------------------------

def get_customer_features(
    feature_result: Dict[str, Any],
) -> pd.DataFrame:
    """Return customer features from the feature result."""

    return feature_result.get(
        "customer_features",
        pd.DataFrame(),
    )


def get_product_features(
    feature_result: Dict[str, Any],
) -> pd.DataFrame:
    """Return product features from the feature result."""

    return feature_result.get(
        "product_features",
        pd.DataFrame(),
    )


def get_sales_time_series(
    feature_result: Dict[str, Any],
) -> pd.DataFrame:
    """Return forecasting time series."""

    return feature_result.get(
        "sales_time_series",
        pd.DataFrame(),
    )


def get_anomaly_features(
    feature_result: Dict[str, Any],
) -> pd.DataFrame:
    """Return anomaly-detection feature matrix."""

    return feature_result.get(
        "anomaly_features",
        pd.DataFrame(),
    )